#!/usr/bin/env python3
"""
Build index.md from data/releases.json.

This is a convenience file for browsing the repo on GitHub. The public site
uses index.html + data/releases.json.
"""

from __future__ import annotations

import json
from pathlib import Path


ICON_BY_CATEGORY = {
    "Feature": "🚀",
    "Improvement": "✨",
    "Security": "🔒",
    "Internal": "🛠️",
    "Update": "📦",
}


def main() -> None:
    root = Path(".")
    data_path = root / "data" / "releases.json"
    out_path = root / "index.md"

    obj = json.loads(data_path.read_text(encoding="utf-8"))
    items = obj.get("items") or []

    lines = [
        "# EHS Dashboard — Release Notes",
        "",
        "This page is auto-generated by CI. See `releases/` for individual release notes.",
        "",
        "## Latest Updates",
        "",
    ]

    for it in items:
        title = (it.get("title") or "").strip() or it.get("id") or "Release"
        path = (it.get("path") or "").strip()
        date = (it.get("date") or "").strip()
        display_category = (it.get("display_category") or it.get("category") or "Update").strip()
        icon = ICON_BY_CATEGORY.get(display_category, "📦")

        # Use ISSUE marker for aggregated notes.
        prefix = "ISSUE" if str(it.get("id", "")).startswith("ISSUE_") else (date or "Release")
        if not path:
            continue
        lines.append(f"- **{prefix}** — {icon} **{display_category}**: [{title}]({path})")

    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()

